// ── tmux config generation ───────────────────────────
function generateTmuxConfig() {
  const lines = [];

  lines.push('# tmux Configuration');
  lines.push('# Generated by Dotfiles Config Generator');
  lines.push('');

  // Prefix key
  if (tmuxAnswers.prefix && tmuxAnswers.prefix !== 'C-b') {
    lines.push('# Change prefix key');
    lines.push('unbind C-b');
    lines.push(`set -g prefix ${tmuxAnswers.prefix}`);
    lines.push(`bind ${tmuxAnswers.prefix} send-prefix`);
    lines.push('');
  }

  // Basic settings
  lines.push('# Basic settings');
  if (tmuxAnswers.mouse) {
    lines.push('set -g mouse on');
  }
  if (tmuxAnswers.baseIndex) {
    lines.push('set -g base-index 1');
    lines.push('setw -g pane-base-index 1');
  }
  if (tmuxAnswers.renumber) {
    lines.push('set -g renumber-windows on');
  }
  if (!tmuxAnswers.autoRename) {
    lines.push('setw -g automatic-rename off');
    lines.push('setw -g allow-rename off');
  }
  if (tmuxAnswers.visualBell) {
    lines.push('set -g visual-bell on');
    lines.push('set -g bell-action any');
  }
  lines.push('set -g escape-time 10');
  lines.push(`set -g history-limit ${tmuxAnswers.historyLimit}`);
  if (tmuxAnswers.focusEvents) {
    lines.push('set -g focus-events on');
  }
  if (tmuxAnswers.clipboard) {
    lines.push('set -g set-clipboard on');
  }
  if (tmuxAnswers.aggressiveResize) {
    lines.push('setw -g aggressive-resize on');
  }
  lines.push(`set -g display-panes-time ${tmuxAnswers.displayPanesTime}`);
  lines.push(`set -g repeat-time ${tmuxAnswers.repeatTime}`);
  lines.push('');

  // Colors
  lines.push('# Colors');
  lines.push(`set -g default-terminal "${tmuxAnswers.terminalType}"`);
  lines.push('');

  // Theme
  const theme = tmuxAnswers.theme;
  if (theme && theme !== 'default') {
    lines.push(`# ${theme.charAt(0).toUpperCase() + theme.slice(1)} theme`);
    const themeColors = getThemeColors(theme);
    lines.push(`set -g status-style "bg=${themeColors.statusBg},fg=${themeColors.statusFg}"`);
    if (tmuxAnswers.activeBorder) {
      lines.push(`set -g pane-active-border-style "fg=${themeColors.activeBorder}"`);
    }
    lines.push(`set -g pane-border-style "fg=${themeColors.border}"`);
    lines.push(`set -g window-status-current-style "bg=${themeColors.activeBg},fg=${themeColors.activeFg}"`);
    lines.push('');
  } else if (tmuxAnswers.activeBorder) {
    lines.push('# Active pane border');
    lines.push('set -g pane-active-border-style "fg=green"');
    lines.push('');
  }

  // Status bar
  lines.push('# Status bar');
  lines.push(`set -g status-position ${tmuxAnswers.statusPosition || 'bottom'}`);
  lines.push(`set -g status-interval ${tmuxAnswers.statusInterval}`);
  lines.push(`set -g status-justify ${tmuxAnswers.statusJustify}`);
  lines.push(`set -g status-left-length ${tmuxAnswers.statusLeftLength}`);
  lines.push(`set -g status-right-length ${tmuxAnswers.statusRightLength}`);

  const leftParts = [];
  const rightParts = [];

  if (tmuxAnswers.statusModules.includes('session')) {
    leftParts.push('[#S]');
  }
  if (tmuxAnswers.statusModules.includes('pane-count')) {
    leftParts.push('[#{window_panes}P]');
  }
  if (tmuxAnswers.statusModules.includes('git')) {
    rightParts.push('#(cd #{pane_current_path}; git rev-parse --abbrev-ref HEAD 2>/dev/null || echo "-")');
  }
  if (tmuxAnswers.statusModules.includes('hostname')) {
    rightParts.push('#H');
  }
  if (tmuxAnswers.statusModules.includes('battery')) {
    rightParts.push('#(cat /sys/class/power_supply/BAT0/capacity 2>/dev/null || pmset -g batt 2>/dev/null | grep -o "[0-9]*%" || echo "N/A")%%');
  }
  if (tmuxAnswers.statusModules.includes('datetime')) {
    rightParts.push('%Y-%m-%d %H:%M');
  }
  if (tmuxAnswers.statusModules.includes('load')) {
    rightParts.push('#(uptime | cut -d "," -f 3-)');
  }
  if (tmuxAnswers.statusModules.includes('uptime')) {
    rightParts.push('#(uptime | sed "s/.*up/up/" | sed "s/,.*user.*//" | xargs)');
  }

  if (leftParts.length > 0) {
    lines.push(`set -g status-left "${leftParts.join(' ')} "`);
  }
  if (rightParts.length > 0) {
    lines.push(`set -g status-right " ${rightParts.join(' | ')}"`);
  }
  lines.push('');

  // Split keys
  const splitKeys = tmuxAnswers.splitKeys;
  if (splitKeys && splitKeys !== 'default') {
    lines.push('# Pane splitting');
    if (splitKeys === 'vim') {
      lines.push('bind | split-window -h');
      lines.push('bind - split-window -v');
    } else if (splitKeys === 'intuitive') {
      lines.push('bind h split-window -h');
      lines.push('bind v split-window -v');
    } else if (splitKeys === 'terminal') {
      lines.push('bind d split-window -h');
      lines.push('bind D split-window -v');
    }
    lines.push('unbind \'"\'');
    lines.push('unbind %');
    lines.push('');
  }

  // Extra bindings
  const extraBindings = tmuxAnswers.extraBindings;
  if (extraBindings.length > 0) {
    lines.push('# Additional keybindings');

    if (extraBindings.includes('vim-navigation')) {
      lines.push('# Vim-style pane navigation');
      lines.push('bind h select-pane -L');
      lines.push('bind j select-pane -D');
      lines.push('bind k select-pane -U');
      lines.push('bind l select-pane -R');
    }

    if (extraBindings.includes('vim-resize')) {
      lines.push('# Vim-style pane resizing');
      lines.push('bind -r H resize-pane -L 5');
      lines.push('bind -r J resize-pane -D 5');
      lines.push('bind -r K resize-pane -U 5');
      lines.push('bind -r L resize-pane -R 5');
    }

    if (extraBindings.includes('reload')) {
      lines.push('# Reload configuration');
      lines.push('bind r source-file ~/.tmux.conf \\; display "Config reloaded!"');
    }

    if (extraBindings.includes('copy-mode-vi')) {
      lines.push('# Vi mode for copy');
      lines.push('setw -g mode-keys vi');
      lines.push('bind -T copy-mode-vi v send-keys -X begin-selection');
      lines.push('bind -T copy-mode-vi y send-keys -X copy-selection-and-cancel');
    }

    if (extraBindings.includes('swap-panes')) {
      lines.push('# Swap panes');
      lines.push('bind { swap-pane -U');
      lines.push('bind } swap-pane -D');
    }

    if (extraBindings.includes('synchronize')) {
      lines.push('# Synchronize panes');
      lines.push('bind S setw synchronize-panes');
    }

    if (extraBindings.includes('window-move')) {
      lines.push('# Window navigation with Shift+arrows');
      lines.push('bind -n S-Left previous-window');
      lines.push('bind -n S-Right next-window');
    }

    if (extraBindings.includes('new-window')) {
      lines.push('# New window (tab) with prefix + t');
      lines.push('bind t new-window');
    }

    if (extraBindings.includes('session-switch')) {
      lines.push('# Session switching');
      lines.push('bind ( switch-client -p');
      lines.push('bind ) switch-client -n');
    }

    if (extraBindings.includes('layout-cycle')) {
      lines.push('# Cycle through layouts');
      lines.push('bind Space next-layout');
    }

    if (extraBindings.includes('zoom-pane')) {
      lines.push('# Zoom pane toggle');
      lines.push('bind z resize-pane -Z');
    }

    if (extraBindings.includes('kill-pane')) {
      lines.push('# Kill pane/window without confirmation');
      lines.push('bind x kill-pane');
      lines.push('bind X kill-window');
    }

    if (extraBindings.includes('clear-history')) {
      lines.push('# Clear screen and scrollback');
      lines.push('bind C-l send-keys C-l \\; clear-history');
    }

    lines.push('');
  }

  // Plugins
  const plugins = tmuxAnswers.plugins;
  if (plugins.length > 0) {
    lines.push('# Plugins (tpm)');

    if (plugins.includes('tpm')) {
      lines.push('set -g @plugin \'tmux-plugins/tpm\'');
    }
    if (plugins.includes('sensible')) {
      lines.push('set -g @plugin \'tmux-plugins/tmux-sensible\'');
    }
    if (plugins.includes('resurrect')) {
      lines.push('set -g @plugin \'tmux-plugins/tmux-resurrect\'');
    }
    if (plugins.includes('continuum')) {
      lines.push('set -g @plugin \'tmux-plugins/tmux-continuum\'');
      lines.push('set -g @continuum-restore \'on\'');
    }
    if (plugins.includes('yank')) {
      lines.push('set -g @plugin \'tmux-plugins/tmux-yank\'');
    }
    lines.push('');

    if (plugins.includes('tpm')) {
      lines.push('# Initialize tpm (keep this line at the very bottom)');
      lines.push('run \'~/.tmux/plugins/tpm/tpm\'');
      lines.push('');
    }
  }

  return lines.join('\n');
}

function getThemeColors(theme) {
  const themes = {
    nord: {
      statusBg: '#2E3440',
      statusFg: '#D8DEE9',
      activeBorder: '#88C0D0',
      border: '#4C566A',
      activeBg: '#5E81AC',
      activeFg: '#ECEFF4',
    },
    dracula: {
      statusBg: '#282a36',
      statusFg: '#f8f8f2',
      activeBorder: '#bd93f9',
      border: '#44475a',
      activeBg: '#bd93f9',
      activeFg: '#282a36',
    },
    gruvbox: {
      statusBg: '#282828',
      statusFg: '#ebdbb2',
      activeBorder: '#fe8019',
      border: '#3c3836',
      activeBg: '#fe8019',
      activeFg: '#282828',
    },
    github: {
      statusBg: '#161b22',
      statusFg: '#e6edf3',
      activeBorder: '#dd6620',
      border: '#30363d',
      activeBg: '#dd6620',
      activeFg: '#ffffff',
    },
    tokyonight: {
      statusBg: '#1a1b26',
      statusFg: '#c0caf5',
      activeBorder: '#7aa2f7',
      border: '#3b4261',
      activeBg: '#7aa2f7',
      activeFg: '#1a1b26',
    },
    catppuccin: {
      statusBg: '#1e1e2e',
      statusFg: '#cdd6f4',
      activeBorder: '#cba6f7',
      border: '#45475a',
      activeBg: '#cba6f7',
      activeFg: '#1e1e2e',
    },
    solarized: {
      statusBg: '#002b36',
      statusFg: '#839496',
      activeBorder: '#268bd2',
      border: '#073642',
      activeBg: '#268bd2',
      activeFg: '#fdf6e3',
    },
  };
  return themes[theme] || themes.github;
}

// ── tmux full session preview ──────────────────────────
function buildTmuxPreview() {
  const preview = document.getElementById('tmux-preview');
  if (!preview) return;

  const theme = tmuxAnswers.theme;
  const themeColors = (theme && theme !== 'default') ? getThemeColors(theme) : {
    statusBg: '#333333', statusFg: '#d0d0d0', activeBg: '#005f00', activeFg: '#ffffff',
    activeBorder: '#00d700', border: '#555555',
  };

  // Status bar parts
  const leftParts = [];
  const rightParts = [];
  if (tmuxAnswers.statusModules.includes('session')) leftParts.push('[main]');
  if (tmuxAnswers.statusModules.includes('pane-count')) leftParts.push('[2P]');
  if (tmuxAnswers.statusModules.includes('git')) rightParts.push('main');
  if (tmuxAnswers.statusModules.includes('hostname')) rightParts.push('myhost');
  if (tmuxAnswers.statusModules.includes('battery')) rightParts.push('85%');
  if (tmuxAnswers.statusModules.includes('datetime')) rightParts.push('2026-02-21 14:30');
  if (tmuxAnswers.statusModules.includes('load')) rightParts.push('0.42');
  if (tmuxAnswers.statusModules.includes('uptime')) rightParts.push('up 3d 2h');

  const windowHtml = `<span class="tmux-preview-window">1:zsh</span><span class="tmux-preview-window active" style="background:${themeColors.activeBg};color:${themeColors.activeFg};border-radius:2px">2:vim*</span><span class="tmux-preview-window">3:htop</span>`;

  const statusBarHtml = `<div class="tmux-preview-status" style="background:${themeColors.statusBg};color:${themeColors.statusFg}">
    <span class="tmux-preview-status-left">${leftParts.join(' ')}</span>
    <span class="tmux-preview-status-center">${windowHtml}</span>
    <span class="tmux-preview-status-right">${rightParts.join(' | ')}</span>
  </div>`;

  // Pane borders
  const activeBorderColor = tmuxAnswers.activeBorder ? themeColors.activeBorder : '#00d700';
  const borderColor = themeColors.border || '#555555';
  const fgColor = themeColors.statusFg || '#d0d0d0';

  const prefix = tmuxAnswers.prefix || 'C-b';

  const panesHtml = `<div class="tmux-pane-area">
    <div class="tmux-pane tmux-pane-active" style="border-color:${activeBorderColor}">
      <span class="tmux-pane-label" style="color:${activeBorderColor}">ペイン1 (アクティブ)</span>
      <div class="tmux-pane-content" style="color:${fgColor}">
        <span style="color:#3fb950">user@myhost</span>:<span style="color:#58a6ff">~/projects</span>$ ls<br>
        <span style="color:#8b949e">README.md  src/  tests/</span><br>
        <span style="color:#3fb950">user@myhost</span>:<span style="color:#58a6ff">~/projects</span>$ <span class="tmux-cursor">▌</span>
      </div>
    </div>
    <div class="tmux-pane" style="border-color:${borderColor}">
      <span class="tmux-pane-label" style="color:${borderColor}">ペイン2</span>
      <div class="tmux-pane-content" style="color:${fgColor}">
        <span style="color:#8b949e"># ~/.tmux.conf</span><br>
        <span style="color:#58a6ff">set</span> -g prefix ${prefix}<br>
        <span style="color:#58a6ff">set</span> -g mouse ${tmuxAnswers.mouse ? 'on' : 'off'}<br>
        <span style="color:#8b949e">~</span>
      </div>
    </div>
  </div>`;

  const position = tmuxAnswers.statusPosition || 'bottom';
  preview.innerHTML = position === 'top'
    ? statusBarHtml + panesHtml
    : panesHtml + statusBarHtml;
}

// ── tmux result rendering ─────────────────────────────
function renderTmuxResult() {
  const config = generateTmuxConfig();
  document.getElementById('tmux-config-output').innerHTML = highlightConf(config);
  buildTmuxPreview();
}

function copyTmuxConfig() {
  const text = document.getElementById('tmux-config-output').innerText;
  navigator.clipboard.writeText(text).then(() => {
    showToast('コピーしました');
  }).catch(() => {
    showToast('コピーに失敗しました');
  });
}

function downloadTmuxConfig() {
  const text = document.getElementById('tmux-config-output').innerText;
  const blob = new Blob([text], { type: 'text/plain' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = '.tmux.conf';
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
